### ISSUE TITLE
建议添加excelRender的单独渲染

### ISSUE THREAD

**Issue by jilangyangbo** [EddieUp/antd-table-saveas-excel#1]
为了和antd table使用相同的columns,可以在原有的columns中添加excelRender属性区分开原有的render;
因为原有的render可能是弹窗或者其他形式跟excel上显示样式和内容会不同,为了不重写columns,可以添加一个属性excelRender,
单独进行excel上显示处理

**Comment by EddieUp** [comment]
是 网页上显示的单元格内容 和 下载的excel单元格内容 不一样的需求吗?

> 为了和antd table使用相同的columns,可以在原有的columns中添加excelRender属性区分开原有的render;
> 因为原有的render可能是弹窗或者其他形式跟excel上显示样式和内容会不同,为了不重写columns,可以添加一个属性excelRender,
> 单独进行excel上显示处理

**Comment by EddieUp** [comment]
#2
