### ISSUE TITLE
加入dataSource字段空值的异常处理

### ISSUE THREAD

**Issue by alienzhangyw** [EddieUp/antd-table-saveas-excel#10]
场景：dataIndex是string或者嵌套的string[]，从后端获取的dataSource中的对应字段可能是空或者undefined，此时生成excel会报错。举个例子，dataIndex = ['version', 'modifier']，某些行数据可能version字段是undefined，此时导出excel会报错：
![image](https://user-images.githubusercontent.com/58874541/127114653-559b2033-d259-4af4-8bf4-2033a4a1a703.png)
希望的效果：和antd Table一样空数据就显示为空，不报错。

另外一个请求，IExcelColumn能否加入一个参数，指定该列是否加入excel中。因为网页上展示的某些列是无法或者不需要生成到excel中的，手动从columns剔除太麻烦了。

**Comment by EddieUp** [comment]
好的，我看一下

**Comment by EddieUp** [comment]
> 好的，我看一下

文档和包都已更新，2.1.3
添加了__ignore__参数配置过滤列
