### ISSUE TITLE
导出的时候报错了，但是我无法知道这是如何造成的

### ISSUE THREAD

**Issue by BobbleHatkjh** [EddieUp/antd-table-saveas-excel#11]
## TypeError: props.children.reduce is not a function

getChildren

.ant-design-pro/node_modules/antd-table-saveas-excel/dist/index.esm.js:597

```
  594 |     props = _ref.props;
  595 | 
  596 | if (typeof props.children === 'string') return props.children;
> 597 | return props.children.reduce(function (prev, cur) {
      | ^  598 |   if (typeof prev === 'string') {
  599 |     return prev + ' ' + getChildren(cur);
  600 |   }
```

![83A60222-3078-4526-B464-FDC148356681](https://user-images.githubusercontent.com/35591106/129300907-680c86eb-ec91-484a-a794-4424aca5f2f3.png)

**Comment by BobbleHatkjh** [comment]
啊我找到了这个问题的原因，如果表格中key值是number类型的话就通不过这里的逻辑（既没有命中string类型的返回，也无法通过数组遍历），希望作者能改下这里的错误啦

![image](https://user-images.githubusercontent.com/35591106/129314698-91635f87-bd77-449e-a312-474ffc82b9d2.png)

**Comment by BobbleHatkjh** [comment]
啊我找到了问题所在：
当render里当前显示的元素被其他组件包裹的时候就有可能会出现这个错误，
比如我这个用tooltip包裹了下，希望作者能修改一下呀

![image](https://user-images.githubusercontent.com/35591106/129316495-762501d7-250a-44ee-b438-0b097f21d364.png)

**Comment by EddieUp** [comment]
> 啊我找到了问题所在：
> 当render里当前显示的元素被其他组件包裹的时候就有可能会出现这个错误，
> 比如我这个用tooltip包裹了下，希望作者能修改一下呀
> 
> ![image](https://user-images.githubusercontent.com/35591106/129316495-762501d7-250a-44ee-b438-0b097f21d364.png)

其实关于render的处理，我还没找到一个比较好的方案来找到要显示的值，所以开放了excelRender这个字段，用来渲染下载的显示内容。当然，这个报错是得处理一下。🙏

**Comment by Kennn-dev** [comment]
i got the same problem 😪
