### ISSUE TITLE
导出之后excel无法打开

### ISSUE THREAD

**Issue by BobbleHatkjh** [EddieUp/antd-table-saveas-excel#16]
我有一个表头是叫 is_active

然后我发现数据中如果这种带转义字符的（这个应该是java里的一个方块），导出之后文件就无法打开了，我贴了下其中一个例子，这个有可能解决吗

is_active: "\u0001"

**Comment by EddieUp** [comment]
> 我有一个表头是叫 is_active
> 
> 然后我发现数据中如果这种带转义字符的（这个应该是java里的一个方块），导出之后文件就无法打开了，我贴了下其中一个例子，这个有可能解决吗
> 
> is_active: "\u0001"

可以用codepen或者其他在线工具发个demo？

**Comment by EddieUp** [comment]
我的wps可以打开，但是内容没了，可以下载前再转译一下吧
