### ISSUE TITLE
是否有辦法removeColumn

### ISSUE THREAD

**Issue by evolution9502** [EddieUp/antd-table-saveas-excel#18]
如題，文檔中只有addColumns用以額外添加column
但由於我是使用antd pro中的proTable
因為要優化proTable自帶的搜索，有針對相同dataIndex的資料做了重複的column(一個hideInTable, 一個hideInSearch)
所以我需要讓其中一個column能夠從導出的表單中隱藏或移除
但目前似乎尚未支持這個用法?
我嘗試過在屬性中添加excelRender: false或excelRender: null，並不起作用  (excelRender: -1會報錯)
若是已經有可行的移除column方法還請不吝相告

**Comment by evolution9502** [comment]
我又耍笨了
__ignore__:true,
就可以...

**Comment by loocor** [comment]
可以对 column 做过滤，比如 `.addColumns(columns.filter((col) => col?.key != 'action') as IExcelColumn[])`
