### ISSUE TITLE
Centering Header Titles

### ISSUE THREAD

**Issue by Tuhama** [EddieUp/antd-table-saveas-excel#19]
using this snippet doesn't seem to center header title (it works for body cells), headers are only centered when they span more than one column.
` excel
    .setTHeadStyle({
      h: "center",
    })`

**Comment by EddieUp** [comment]
fixed: https://github.com/EddieUp/antd-table-saveas-excel/commit/77d5f921f27c28164398234b968b69b3bb7455c8

**Comment by Tuhama** [comment]
thnks 👍
