### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by aseph8083** [EddieUp/antd-table-saveas-excel#20]
i'm using nextjs

Server Error
ReferenceError: navigator is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.<anonymous>
/node_modules/antd-table-saveas-excel/dist/index.js (173:40)

**Comment by varKeytrap** [comment]
Go to 

`/node_modules/antd-table-saveas-excel/dist/index.js (173:40)`

replace 

```javascript
var isMac = /macintosh|mac os x/i.test(navigator.userAgent.toLowerCase()); // 获取默认的字体

function getDefaultFontName() {
  if (isMac) {
    return 'PingFang SC';
  }

  return 'Microsoft YaHei';
}
```

with

```javascript
function getDefaultFontName() {
  if (typeof global.navigator === 'undefined')
    return 'Microsoft YaHei';
  
  var isMac = /macintosh|mac os x/i.test(navigator?.userAgent.toLowerCase());
  return isMac ? 'PingFang SC' : 'Microsoft YaHei';
}
```

**Comment by aseph8083** [comment]
> Go to
> 
> `/node_modules/antd-table-saveas-excel/dist/index.js (173:40)`
> 
> replace
> 
> ```js
> var isMac = /macintosh|mac os x/i.test(navigator.userAgent.toLowerCase()); // 获取默认的字体
> 
> function getDefaultFontName() {
>   if (isMac) {
>     return 'PingFang SC';
>   }
> 
>   return 'Microsoft YaHei';
> }
> ```
> 
> with
> 
> ```js
> function getDefaultFontName() {
>   if (typeof global.navigator === 'undefined')
>     return 'Microsoft YaHei';
>   
>   var isMac = /macintosh|mac os x/i.test(navigator?.userAgent.toLowerCase());
>   return isMac ? 'PingFang SC' : 'Microsoft YaHei';
> }
> ```

Thank you so much
