### ISSUE TITLE
表格下载的时候 表头render自定义的函数解析有问题

### ISSUE THREAD

**Issue by yaya1286249672** [EddieUp/antd-table-saveas-excel#26]
function getChildren(data) {
  var _ref = data || {},
      props = _ref.props;

  if (typeof props.children === 'string') return props.children;
  return props.children.reduce(function (prev, cur) {
    if (typeof prev === 'string') {
      return prev + ' ' + getChildren(cur);
    }

    return getChildren(prev) + ' ' + getChildren(cur);
  }, '');
}

**Comment by EddieUp** [comment]
> function getChildren(data) { var _ref = data || {}, props = _ref.props;
> 
> if (typeof props.children === 'string') return props.children; return props.children.reduce(function (prev, cur) { if (typeof prev === 'string') { return prev + ' ' + getChildren(cur); }
> 
> ```
> return getChildren(prev) + ' ' + getChildren(cur);
> ```
> 
> }, ''); }

给个问题复现的在线例子吧

**Comment by yaya1286249672** [comment]
比如render:(v)=>{
return <div>
{v}
<span>
100%
</span>
</div>
}
