### ISSUE TITLE
text is always undefined when rendering a column 

### ISSUE THREAD

**Issue by egachi** [EddieUp/antd-table-saveas-excel#27]
When rendering inside a column to get the current value from the database, it is always sending undefined values. 

```
 { title: 'Test',  dataIndex: 'test' , __style__: RowStyle(), 
            render: (text, row, index) => {
                if(text)
                    return text;
                else
                    return <a>Option</a>;
            }
  },
```

Any other way to get the value in the render method? 

Thanks

**Comment by egachi** [comment]
I found it, with the row.field should be enough. Thanks

**Comment by aseph8083** [comment]
> I found it, with the row.field should be enough. Thanks

can you share an example?
