### ISSUE TITLE
文件格式错误

### ISSUE THREAD

**Issue by yushixin** [EddieUp/antd-table-saveas-excel#3]
mac环境下 实际到处为 .zip文件 ，不是.xlsx

**Comment by EddieUp** [comment]
> mac环境下 实际到处为 .zip文件 ，不是.xlsx

你打印看一下最后导出时saveAs的参数，需要带上后缀

**Comment by EddieUp** [comment]
> mac环境下 实际到处为 .zip文件 ，不是.xlsx

一般是导出的名称的问题

**Comment by yushixin** [comment]
const excel = new Excel();
          excel
            .addSheet('test')
            .addColumns(_column_info)
            .addDataSource(_data)
            .saveAs('测试.xlsx');


写的跟demo是一样的

**Comment by EddieUp** [comment]
> ```
>       const excel = new Excel();
>       excel
>         .addSheet('test')
>         .addColumns(_column_info)
>         .addDataSource(_data)
>         .saveAs('测试.xlsx');
> ```
> 
> 写的跟demo是一样的

可以提供一份最小可复现的代码吗？

**Comment by EddieUp** [comment]
> ```
>       const excel = new Excel();
>       excel
>         .addSheet('test')
>         .addColumns(_column_info)
>         .addDataSource(_data)
>         .saveAs('测试.xlsx');
> ```
> 
> 写的跟demo是一样的

下载这个例子里面的：https://eddieup.github.io/antd-table-saveas-excel/4examples，
如果有问题，提供一下系统信息

**Comment by EddieUp** [comment]
> ```
>       const excel = new Excel();
>       excel
>         .addSheet('test')
>         .addColumns(_column_info)
>         .addDataSource(_data)
>         .saveAs('测试.xlsx');
> ```
> 
> 写的跟demo是一样的

如果着急的话可以尝试自己实现下载逻辑
```
const excel = new Excel();
      excel
        .addSheet('test')
        .addColumns(_column_info)
        .addDataSource(_data)
        .file.saveAs('blob', true).then(data => {
            // 自己的下载实现
          })
````
