### ISSUE TITLE
custom header

### ISSUE THREAD

**Issue by hellobq** [EddieUp/antd-table-saveas-excel#4]
hello, can this code base support custom header ? like this: 

![image](https://user-images.githubusercontent.com/29953650/103182781-f8e06480-48e8-11eb-976f-c948fd7f0fe0.png)

**Comment by EddieUp** [comment]
Above the table header?

**Comment by hellobq** [comment]
> Above the table header?

yeah. do you support this feature now? please give me a demo. thanks a lot.

**Comment by EddieUp** [comment]
> > Above the table header?
> 
> yeah. do you support this feature now? please give me a demo. thanks a lot.

support a row header, like this:
```
const columns = [
  {
    title: 'i am header',
    children: [
      {
        title: 'Name',
        dataIndex: 'name',
      },
      {
        title: 'Age',
        dataIndex: 'age',
        render: renderContent,
      },
      {
        title: 'Home phone',
        colSpan: 2,
        dataIndex: 'tel',
      },
      {
        title: 'Phone',
        colSpan: 0,
        dataIndex: 'phone',
        render: renderContent,
      },
      {
        title: 'Address',
        dataIndex: 'address',
        render: renderContent,
      },
    ],
  },
]
```
not support more rows merged now, support for the next version😄
