### ISSUE TITLE
不支持ie啊， 使用了那些不兼容的东西吗， ie11都打不开啊， import 后项目直接挂了， 有没有什么办法能避免下， 至少在ie中不能用， 但是项目不会挂啊

### ISSUE THREAD

**Issue by 15531400827** [EddieUp/antd-table-saveas-excel#6]
![微信图片_20210116211014](https://user-images.githubusercontent.com/25213847/104812793-aaffb200-583f-11eb-8450-459df986687a.png)
引入后在ie中项目直接报错了

**Comment by 15531400827** [comment]
![微信图片_20210116211957](https://user-images.githubusercontent.com/25213847/104812915-9d96f780-5840-11eb-8208-f26ca73a9916.png)
点进去是这个错

**Comment by EddieUp** [comment]
> ![微信图片_20210116211957](https://user-images.githubusercontent.com/25213847/104812915-9d96f780-5840-11eb-8208-f26ca73a9916.png)
> 点进去是这个错
看不到图，要不加你微信看看？

**Comment by EddieUp** [comment]
> ![微信图片_20210116211957](https://user-images.githubusercontent.com/25213847/104812915-9d96f780-5840-11eb-8208-f26ca73a9916.png)
> 点进去是这个错

打包出来的是es模块，你的webpack是不是排除了node_modules的兼容性处理？

**Comment by 15531400827** [comment]
> > ![微信图片_20210116211957](https://user-images.githubusercontent.com/25213847/104812915-9d96f780-5840-11eb-8208-f26ca73a9916.png)
> > 点进去是这个错
> 
> 打包出来的是es模块，你的webpack是不是排除了node_modules的兼容性处理？

我用的ant-design-pro 1.x版本啊， webpack是框架配的， 我也没懂过， ie9都行兼容性应该挺好的

**Comment by EddieUp** [comment]
如果只是import 不使用会报错吗？

**Comment by 15531400827** [comment]
> 如果只是import 不使用会报错吗？

会的， import就报错， 项目直接打不开， 我看你那个官网在ie11也打不开
![image](https://user-images.githubusercontent.com/25213847/104813817-83f8ae80-5846-11eb-8069-e4578cf084c1.png)

**Comment by 15531400827** [comment]
![微信图片_20210116220309](https://user-images.githubusercontent.com/25213847/104813834-a2f74080-5846-11eb-96fb-df3dc89a4e05.png)


> > 如果只是import 不使用会报错吗？
> 
> 会的， import就报错， 项目直接打不开， 我看你那个官网在ie11也打不开
> ![image](https://user-images.githubusercontent.com/25213847/104813817-83f8ae80-5846-11eb-8069-e4578cf084c1.png)

**Comment by EddieUp** [comment]
我看看是什么问题

**Comment by EddieUp** [comment]
我用了create-react-app创建的项目，解决本身在ie11中的兼容性后，再引用插件是正常的![Image](https://i.imgur.com/AdosBfj.jpg)

**Comment by EddieUp** [comment]
你不引入该插件的情况下应该也是会报错的吧，这个你要确认本身项目能否跑起来

**Comment by EddieUp** [comment]
插件本身不是umd 模式，不会打包兼容库，所有的高级语法你可以通过项目本身处理，你可以搜一下babel polyfill 的用法

**Comment by EddieUp** [comment]
插件本身不是umd 模式，不会打包兼容库，所有的高级语法你可以通过项目本身处理，你可以搜一下babel polyfill 的用法

**Comment by 15531400827** [comment]
babel polyfill 这东西 ant design pro框架肯定是带的吧， 我不引入你这个插件 ie9都可以打开， 引入了ie11都打不开了...， 昨天项目发版， 找了一晚上问题， 后来去掉这个插件 ie上就好了

**Comment by 15531400827** [comment]
我网上搜搜babel polyfill这东西看看

**Comment by EddieUp** [comment]
现在回看你一开始发的图片，是不支持字符串模板的写法吗？你项目中没有使用es6,7,8的语法吗?

**Comment by 15531400827** [comment]
使用了啊， 我很多地方都用了

**Comment by EddieUp** [comment]
那你引入polyfill好了吗

**Comment by 15531400827** [comment]
还是不行， 我拉了下你这个项目的代码
![image](https://user-images.githubusercontent.com/25213847/104817457-5b7baf00-585c-11eb-8747-37ff8a78724a.png)
引入了polyfill在ie下也是报错

**Comment by EddieUp** [comment]
不要在这个项目里试了，我用的文档框架有点问题

**Comment by 15531400827** [comment]
> 现在回看你一开始发的图片，是不支持字符串模板的写法吗？你项目中没有使用es6,7,8的语法吗?
挺奇怪的， 不知道一个模板字符串为什么会报错， 我项目中很多地方用了模板字符串啊

**Comment by EddieUp** [comment]
我猜的，你试一下在html 引入https://cdn.bootcdn.net/ajax/libs/babel-polyfill/7.0.0-beta.32/polyfill.min.js ，放在前面

**Comment by 15531400827** [comment]
也不行， 我那个import的其实就是生效了
![image](https://user-images.githubusercontent.com/25213847/104817722-e7420b00-585d-11eb-83a2-8b09bf112624.png)
引入这个说是只允许引入一个polyfill
然后去掉那个import的只在html里面引入这个还是报一样的错误

**Comment by EddieUp** [comment]
你的报错和我的不一样，我的是语法报错，你的是载入模块报错？你点进去看看是哪里报错

**Comment by EddieUp** [comment]
你是不是懒加载了代码，你试试不要懒加载

**Comment by EddieUp** [comment]
你可以看一下这个链接https://stackoverflow.com/questions/58256536/unhandled-rejection-chunkloaderror-loading-chunk-1-failed，感觉有点像

**Comment by 15531400827** [comment]
> 你的报错和我的不一样，我的是语法报错，你的是载入模块报错？你点进去看看是哪里报错

你那边如果对这个问题有兴趣的话可以加个微信， 我整理一份ant-design-pro1.x的框架给你看看，和我这环境一样的， 我微信17612511772

**Comment by EddieUp** [comment]
我加你了，明天再看吧，困死了
