### ISSUE TITLE
是否支持多个sheet？

### ISSUE THREAD

**Issue by gyokuhou** [EddieUp/antd-table-saveas-excel#8]
DEMO中都是单sheet的表格文件，请问是否支持导出多个sheet？

**Comment by EddieUp** [comment]
可以参考这个例子：https://codesandbox.io/s/distracted-browser-bvvsu?fontsize=14&hidenavigation=1&theme=dark

**Comment by gyokuhou** [comment]
well done.This example of exporting multiple sheets can be added to DEMO.
